import os
import google.generativeai as genai
from supabase import create_client

# 1. Setup Connections
GEMINI_KEY = os.environ.get("GEMINI_API_KEY")
SB_URL = os.environ.get("SUPABASE_URL")
SB_KEY = os.environ.get("SUPABASE_KEY")

genai.configure(api_key=GEMINI_KEY)
supabase = create_client(SB_URL, SB_KEY)

def generate_article():
    # Using the 3.1 Flash Lite for the 500 RPD limit!
    # Adding 'tools' for Search Grounding to get real 2026 news
    model = genai.GenerativeModel(
        model_name='gemini-3.1-flash-lite',
        tools=[{'google_search_retrieval': {}}] 
    )
    
    prompt = """
    Search for the most recent trending tech or AI news from today, April 29, 2026. 
    Write a 1000-word SEO-optimized article based on what you find. 
    Use HTML tags (h1, h2, p, ul, li) for formatting. 
    Make it look like a professional news report.
    """
    
    # Generate content with "Grounding" (Real-time web search)
    response = model.generate_content(prompt)
    article_html = response.text
    
    # 2. Save to Supabase
    data = {
        "domain_name": "news.raappo.cf", 
        "title": "2026 Ghost Tech Report",
        "body_content": article_html
    }
    supabase.table("content_farm").insert(data).execute()
    
    # 3. Create the index.html for Cloudflare Pages
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Ghost Industry News</title>
            <style>
                body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: auto; padding: 40px; line-height: 1.6; color: #333; }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
                h2 {{ color: #34495e; margin-top: 30px; }}
            </style>
        </head>
        <body>
            {article_html}
            <hr>
            <p style="text-align: center; color: #999;">Generated by Raappo Ghost Industry &copy; 2026</p>
        </body>
        </html>
        """)

if __name__ == "__main__":
    generate_article()
